name = 'DATALIFE (Alpha) | 01'
port = 7788
players = 128
# password = 'ultra-password'
announce = false
# token = 'YOUR_TOKEN'
gamemode = 'DATALIFE v0.1'
website = 'dataliferp.com'
language = 'pt-br'
description = 'alt:V Sample Server'
modules = ['js-module']
resources = [
    'main',
    'webviews',
]
enableSyncedMetaData = false
debug=true