export const maleHairNames = [
  'Close Shave',
  'Buzzcut',
  'Faux Hawk',
  'Shaved Sides Slicked Back',
  'Raised Front Same Length',
  'Col De Sacs and Long Back',
  'Close Shave and Loose Mohawk',
  'Ponytail',
  'Corn Rows',
  'Slicked Back Curly Back',
  'Slicked Back',
  'Spiked',
  'Short Bowl Cut',
  'Messy Long Length',
  'Dreads',
  'Straight Long Length',
  'Curly Long',
  'Straight Long Partial Messy',
  'Side Part Front Short',
  'Slicked Back Short',
  'Side Part Front Long',
  'Razer Side Part Slick',
  'Mullet',
  'Nightvision',
  'Corn Rows',
  'Starfish Corn Rows',
  'Zig Zag Corn Rows',
  'Large Snakelike Corn Rows',
  'Small Snakelike Corn Rows',
  'Side Swirl Corn Rows',
  'Flat Top',
  'Front Crown Long Back',
  'Shaved Sided Slicked Back',
  'Side Parted Shaved Sides',
  'Mohawk',
  'Messy Long Back',
  'Center Parted Bob',
  'Buzz Cut',
  'Faux Hawk',
  'Shaved Sides Slicked Back',
  'Raised Front Same Length',
  'Col De Sacs and Long Back',
  'Close Shave and Loose Mohawk',
  'Ponytail',
  'Corn Rows',
  'Slicked Back Curly Back',
  'Slicked Back',
  'Spiked',
  'Short Bowl Cut',
  'Messy Long Length',
  'Dreads',
  'Straight Long Length',
  'Curly Long',
  'Straight Long Partial Messy',
  'Side Part Front Short',
  'Slicked Back Short',
  'Side Part Front Long',
  'Razer Side Part Slick',
  'Mullet',
  'Corn Rows',
  'Starfish Corn Rows',
  'Zig Zag Corn Rows',
  'Large Snakelike Corn Rows',
  'Small Snakelike Corn Rows',
  'Side Swirl Corn Rows',
  'Flat Top',
  'Front Crown Long Back',
  'Shaved Sided Slicked Back',
  'Side Parted Shaved Sides',
  'Mohawk',
  'Messy Long Back',
  'Center Parted Bob',
  'Shaved Sides Flat Top',
  'Shaved Sides Short Top',
  'Elvis',
];

export const femaleHairNames = [
  'Close Shave',
  'Short Bob',
  'Bob',
  'Pigtails',
  'Ponytail',
  'Braided Mohawk',
  'Braids',
  'Bob',
  'Faux Hawk',
  'French Twist',
  'Long Bob',
  'Loose Tied Ponytail',
  'Pixie',
  'Side Parted Shaved Bangs',
  'Top Knot',
  'Wavy Long',
  'Messy Tied Bandana',
  'Messy Bun with Cropped Bangs',
  'Bob with Feathers',
  'Tight Bun Cropped Bangs',
  'Frizzy Curly Afro',
  'Messy Wavy Bangs',
  'Tight Top Bun Braided',
  'Mullet',
  'Night Vision',
  'Braided Corn Rows',
  'Center Part Braided Corn Rows',
  'Diamond Corn Rows',
  'Pigtails with Bangs',
  'Star Braided Corn Rows',
  'Vertical Shaved Corn Rows',
  'Loose Tied Ponytail',
  'Short Mullet',
  'Shaved Sides Slicked Back',
  'Side Parted Shaved Bangs',
  'Mohawk',
  'Tied Pigtails with Bandana',
  'The Karen',
  'Center Parted Bob',
  'Pixie',
  'Bob',
  'Pigtails',
  'Loose Tied Ponytail',
  'Braided Mohawk',
  'Braids',
  'Straight Bob',
  'Faux Hawk',
  'French Twist',
  'Long Bob',
  'Ponytail Bun',
  'Pixie',
  'Side Parted Shaved Bangs',
  'Top Knot',
  'Wavy Long',
  'Messy Tied Bandana',
  'Messy Top Knot with Bangs',
  'Bob with Feathers',
  'Tight Bun Cropped Bangs',
  'Frizzy Curly Afro',
  'Messy Wavy Bangs',
  'Tight Top Bun Braided',
  'Mullet',
  'Corn Rows',
  'Center Parted Corn Rows',
  'Diamond Corn Rows',
  'Pigtails',
  'Star Braided Corn Rows',
  'Vertical Shaved Corn Rows',
  'Loosely Tied Ponytail',
  'Short Mullet',
  'Shaved Sides Slicked Back',
  'Side Parted Shaved Bangs',
  'Mohawk',
  'Tied Pigtails with Bandana',
  'The Karen',
  'Pixie Bob',
  'Tight Pony Tail Bun',
  'Pixie Cut',
  'Elvis',
];
